### ISSUE TITLE
Question about the ensemble attack

### ISSUE THREAD

**Issue by jdg900** [JHL-HUST/VT#2]
Hello.
First of all, thank you for providing your code.
I have a question about your implementation of ensemble attack in vmi_di_ti_si_fgsm.py.
As you mentioned in your paper, I averaged the logits from four normally trained models in batch_grad and graph function. However, when i ran the code, error(cuda out of memory) occur, even if i reduced the batch size. Could you let me know environment for ensemble attack or provide the code for ensemble attack ? 
(My GPU : Titan RTX 24Gb)
I will wait for your reply. 

Thank you!

**Comment by Ke-messi** [comment]
I have a problem similar to yours. How did you solve it？

**Comment by xiaosen-wang** [comment]
hi, it might be out of memory. Such an attack needs a very large memory. You can load each model on a single GPU.
