### ISSUE TITLE
Different success rates when reproducing results from Table 1

### ISSUE THREAD

**Issue by psandovalsegura** [JHL-HUST/VT#5]
The differences in success rates are minor, but I wanted to check whether this difference is expected (and if so, why?). I chose to reproduce two arbitrary attack rows of Table 1 from the paper where the Inc-v3 is used: MI-FGSM and VNI-FGSM.

**Steps taken:**
1. Downloaded data and models from provided README link.
2. Ran `mi_fgsm.py` followed by `simple_eval.py`, then logged results.
3. Ran `vni_fgsm.py` followed by `simple_eval.py`, then logged results.

**Results for MI-FGSM:**
|        |     Model | Attack     |  Inc-v3  |  Inc-v4  |  IncRes-v2  |  Res-101  |  Inc-v3_ens3  |  Inc-v3_ens4  |  IncRes-v2_ens  |
|--------|----------:|------------|----------|----------|-------------|-----------|---------------|---------------|-----------------|
| Paper  |   Inc-v3  |   MI-FGSM  |   100.0  |   45.3   |   42.9      |   36.1    |   13.9        |   13.2        |   6.2           |
| My run |   Inc-v3  |   MI-FGSM  |   100.0  |   43.6   |   42.4      |   35.7    |   13.1        |   12.8        |   6.2           |

**Results for VNI-FGSM:**
|        |     Model | Attack      |  Inc-v3  |  Inc-v4  |  IncRes-v2  |  Res-101  |  Inc-v3_ens3  |  Inc-v3_ens4  |  IncRes-v2_ens  |
|--------|----------:|-------------|----------|----------|-------------|-----------|---------------|---------------|-----------------|
| Paper  |   Inc-v3  |   VNI-FGSM  |   100.0  |   76.1   |   74.8      |   65.7    |   34.3        |   32.7        |   19.4          |
| My run |   Inc-v3  |   VNI-FGSM  |   100.0  |   76.5   |   74.9      |   66.0    |   35.0        |   32.8        |   18.8          |

In the case of MI-FGSM, my run shows that the attack sometimes underperforms reported results (by at most 1.7%). I haven't checked other rows of the table, but thought I should surface this and ask about it. Thanks!

**Comment by xiaosen-wang** [comment]
Hello, it is expected that there is a slight difference for our method due to the randomly sampled images for variance tunning. It seems fun.

**Comment by psandovalsegura** [comment]
Got it. Thanks for the response.
