### ISSUE TITLE
代码运行报错

### ISSUE THREAD

**Issue by CodeLocked** [JHL-HUST/VT#7]
您好！我在运行您的代码时候，程序报错最后一行提示找不到dev_data/val_rs文件，我将val_rs.csv的后缀名删除后，又报错提示找不到dev_data/val_rs.csv，我全部加上后，还是报错提示找不到dev_data/val_rs文件。
请问该如何解决

**Comment by xiaosen-wang** [comment]
你的路径需要放到正确目录下面
